services:
  ddmf-container:
    container_name: ${DISCORD_BOT_IDENTIFIER}
    build:
      context: ./build
      dockerfile: ddmf/Dockerfile

    env_file:
      - .env

    volumes:
      - ./logs:/logs

    restart: unless-stopped
