services:
  ddmf-container:
    container_name: nas-uptime-monitor
    build:
      context: ./build
      dockerfile: ddmf/Dockerfile

    env_file:
      - .env

    volumes:
      - ./logs:/logs

    restart: unless-stopped
